[package]
name = "flatfile"
version = "0.1.2"
authors = ["mhg <mhg@urml.eu>"]

[dependencies]
zstd = "*"
lz4 = "*"
brotli2 = "*"
adler32 = "*"
memmap = "*"
regex = "1"
tiny-keccak = { version = "2.0.0", features = ["shake"] }
